#@ load("@ytt:data", "data")

ingress:
  enabled: true
  hostname: #@ "kubeapps.{}".format(data.values.ingress.domain)
  tls: true
  extraTls:
  - hosts:
    - #@ "kubeapps.{}".format(data.values.ingress.domain)
    secretName: #@ "{}/{}".format(data.values.ingress.contour_tls_namespace,data.values.ingress.contour_tls_secret)
postgresql:
  replication:
    enabled: false
