#@ load("@ytt:data", "data")
#@ if hasattr(data.values.harbor, "diskSize"):
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: harbor
  name: harbor-registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: #@ data.values.harbor.diskSize
#@ end

#@ if data.values.psp.cluster_role:
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: harbor
  name: psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: #@ data.values.psp.cluster_role
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
#@ end