#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: concourse-team-controller
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      initContainers:
      - name: grab-fly
        image: #@ "{}/library/python:2.7".format(data.values.registry.dockerhub)
        volumeMounts:
        - name: fly-cmd
          mountPath: /fly-dir
        env:
        - name: CONCOURSE_URL
          valueFrom:
            secretKeyRef:
              name: controller-secrets
              key: concourse_url
        command: 
        - sh
        - -c
        - |
          CONCOURSE_URL=$(echo $CONCOURSE_URL | tr -d '\n')
          wget -nv -O fly "$CONCOURSE_URL/api/v1/cli?arch=amd64&platform=linux" --no-check-certificate
          chmod +x fly
          mv fly /fly-dir
      containers:
      - name: controller
        image: #@ "{}/library/python:2.7".format(data.values.registry.dockerhub)
        command: ["python", "/hooks/sync.py"]
        livenessProbe:
          exec:
            command: ["/fly-dir/fly", "-t", "concourse", "status"]
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        - name: fly-cmd
          mountPath: /fly-dir
        env:
        - name: CONCOURSE_USERNAME
          valueFrom:
            secretKeyRef:
              name: controller-secrets
              key: concourse_username
        - name: CONCOURSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: controller-secrets
              key: concourse_password
        - name: CONCOURSE_URL
          valueFrom:
            secretKeyRef:
              name: controller-secrets
              key: concourse_url
      volumes:
      - name: hooks
        configMap:
          name: concourse-team-controller
      - name: fly-cmd
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: concourse-team-controller
spec:
  selector:
    app: controller
  ports:
  - port: 80