apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: concourseteams.e2e.tanzu.vmware.com
  namespace: concourse-team-controller
spec:
  group: e2e.tanzu.vmware.com
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              name: 
                type: string
          status:
            type: object
            nullable: true
            properties:
              teamurl:
                type: string
                nullable: true
              error:
                type: string
                nullable: true
  names:
    kind: ConcourseTeam
    plural: concourseteams
    singular: concourseteam
  scope: Namespaced